# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

convolution <- function(a, b) {
    .Call(`_praxi_convolution`, a, b)
}

